cocomu-team/cocomu-fe

- package-lock.json
- package.json
- tsconfig.json
- vite.config.ts
close #8
<br/>
- Path Alias 설정:
import Button from '../../components/_common/atoms/Button'; 을
import Button from '@components/_common/atoms/Button'; 으로 될 수 있도록 import 경로 단순화 하였습니다!
<br/>
<br/>
>
> Chore/#8 Path Alias 설정

- src/components/_common/atoms/ImageTag/index.tsx
- src/components/_common/atoms/ImageTag/style.ts
- src/constants/constants.ts
close #12 
<br/>
- ImageTag 컴포넌트 구현
- 언어별 이미지 매핑 상수 정의
<br/>
<br/>
>
> COC-89 ImageTag 컴포넌트 구현

- src/App.tsx
- src/components/_common/atoms/Toast/index.tsx
- src/components/_common/atoms/Toast/style.ts
- src/main.tsx
close #11
<br/>
- Toast 컴포넌트 구현
- 컴포넌트 호출 시 알림 기능 구
<br/>
>
> feat(#11): Toast 컴포넌트 구현

- src/components/_common/atoms/Stepper/index.tsx
- src/components/_common/atoms/Stepper/style.ts
close #17 
<br/>
- Stepper 컴포넌트 구현
- size, color, children props로 받음
<br/>
>
> COC-129 Stepper 컴포넌트 구현

- src/components/_common/atoms/LoadingSpinner/index.tsx
- src/components/_common/atoms/LoadingSpinner/style.ts
close #16 
<br/>
-  LoadingSpinner 컴포넌트 구현
- color 조건으로 gray, triadic 구분하여 사용
<br/>
<br/>
>
> COC-128 LoadingSpinner 컴포넌트 구현

- src/components/_common/atoms/SearchInput/index.tsx
- src/components/_common/atoms/SearchInput/style.ts
close #22
<br/>
- 검색바 컴포넌트 구현
- placeholder 에 따라 변경 가능
- placeholder : placeholder 내용 작성 (기본값 : '')
- placeholder 미지정 시 placeholder 가 나타나지 않음 
<br/>
<br/>
>
> COC-131: Search Input bar 컴포넌트 구현

- package-lock.json
- package.json
- src/components/_common/atoms/TextEditor/index.tsx
- src/components/_common/atoms/TextEditor/style.css
- tsconfig.json
close #28 
<br/>
TextEditor 컴포넌트는 ReactQuill을 기반으로 하는 WYSIWYG 에디터입니다.
- 작성 모드
```<TextEditor value={content} onChange={setContent} />```
- 읽기 전용 모드 (조회 시 사용):
```<TextEditor value="<p>읽기 전용 모드입니다.</p> <- 백에서 전달받은 게시글 내용 그대로 사용하시면 됩니다" readOnly />```
- 이미지 업로드 버튼 추가
```<TextEditor value={content} onChange={setContent} isImageUploadEnabled />```
에디터 내부의 스타일은 현재 애플리케이션의 스타일 시스템과 별도로 적용됩니다! ( globalStyles 영향 X ) 스타일 지정이 필요한 경우, ```<p>, <h1>, <ol>``` 등의 요소에 대한 className을 확인한 후, 개별적으로 CSS를 추가해야 합니다.
style.css 파일에서 해당 스타일을 확인할 수 있습니다! 원래는 styled를 사용해 작성하려 했으나, Emotion의 theme 설정과 충돌이 발생하여 CSS 파일로 적용했습니다.
<br/>
<br/>
>
> COC-134 TextEditor 컴포넌트 구현

- src/components/_common/atoms/IconButton/style.ts
- src/components/_common/atoms/Radio/index.tsx
- src/components/_common/atoms/Radio/style.ts
- src/components/_common/molecules/RadioField/index.tsx
- src/components/_common/molecules/RadioField/style.ts
- src/components/_common/molecules/RadioOption/index.tsx
- src/components/_common/molecules/RadioOption/style.ts
- src/constants/constants.ts
close #15 
<br/>
- Radio 컴포넌트 구현: 개별 라디오 버튼을 렌더링하며 선택 상태를 관리할 수 있도록 구현
- RadioOption 컴포넌트 구현: 라디오 버튼과 라벨을 포함하는 단위 컴포넌트로 분리하여 재사용성을 높임
- RadioField 컴포넌트 구현: 여러 개의 라디오 옵션을 그룹으로 관리하며, 선택한 값을 변경할 수 있도록 구현
<br/>
<br/>
>
> COC-127 Radio Button 컴포넌트 구현

- src/components/_common/atoms/Toast/index.tsx
- src/components/_common/atoms/Toast/style.ts
- src/components/_common/molecules/ToastList/index.tsx
- src/components/_common/molecules/ToastList/style.ts
- src/main.tsx
- src/stores/useToastStore.ts
close #45 
<br/>
zustand를 사용하여 Toast 메시지를 관리하는 상태 관리 기능을 구현
- `toasts`: 현재 활성화된 Toast 목록을 저장하는 상태 배열
- `alert(message)`, `success(message)`, `error(message)`: 해당 타입의 Toast 메시지를 추가하는 함수
- `removeToast(id)`: 특정 ID의 Toast 메시지를 삭제하는 함수
예제 코드입니다!
```
import { useToastStore } from '@stores/useToastStore';
const { alert, success, error } = useToastStore();
return (
<div>
<button
type='button'
onClick={() => success('성공 메시지!')}
>
성공
</button>
<button
type='button'
onClick={() => error('에러 메시지!')}
>
에러
</button>
<button
type='button'
onClick={() => alert('default 메시지!')}
>
디폴트
</button>
</div>
);
}
```
<br/>
<br/>
> COC-146 Toast 상태 관리 로직 구현

- src/components/_common/MemberCard/index.tsx
- src/components/_common/MemberCard/style.ts
- src/utils/formatDate.ts
close #46 
<br/>
- MemberCard 컴포넌트 구현
- Date를 YYYY.MM.DD 형식으로 변환하는 formatDate 함수 구현
<br/>
```typescript
//App.tsx
import React from 'react';
import MemberCard from '@components/_common/MemberCard';
return (
<div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', height: '100vh', width: '100vh' }}>
<MemberCard
name='이용수'
successCount={10}
failedCount={5}
joinedDate='2025-02-13T13:20:50.197Z'
/>
</div>
);
}
```
<br/>
>
> COC-147 MemberCard 컴포넌트 구현

- src/components/_common/molecules/AvatarGroup/index.tsx
- src/components/_common/molecules/AvatarGroup/style.ts
- src/styles/font.ts
close #49 
<br/>
- AvatarGroup 컴포넌트 구현
- props로 유저 정보, size 받음
- extraSmall 폰트 생성
<br/>
>
> COC-148 AvatarGroup 컴포넌트 구현

- src/components/_common/StudyCard/index.tsx
- src/components/_common/StudyCard/style.ts
- src/components/_common/molecules/ImageTagList/index.tsx
- src/components/_common/molecules/ImageTagList/style.ts
- src/components/_common/molecules/TagList/index.tsx
- src/components/_common/molecules/TagList/style.ts
- src/components/_common/molecules/UserProfile/index.tsx
- src/constants/constants.ts
close #39 
<br/>
- StudyCard 컴포넌트 구현
- TagList, ImageTagList 구현
아직 라우팅 설정을 하지 않아 navigate 기능을 구현하지 않았으며, 이로 인해 id 값들이 사용되지 않아 ESLint 오류가 발생하고 있습니다. 추후 라우팅을 설정할 때 해당 부분을 함께 구현할 예정입니다.
<br/>
<br/>
> COC-143 StudyCard 컴포넌트 구현

- src/components/_common/atoms/Icon/index.tsx
- src/components/_common/atoms/Icon/style.ts
- src/components/_common/atoms/IconButton/index.tsx
- src/components/_common/atoms/IconButton/style.ts
- src/components/_common/atoms/ProfileImage/index.tsx
- src/components/_common/atoms/SearchInput/index.tsx
- src/components/_common/atoms/SearchInput/style.ts
- src/components/_common/atoms/Toast/index.tsx
- src/components/_common/molecules/DropdownList/index.tsx
- src/components/_common/molecules/InputField/index.tsx
close #55 
<br/>
-  아이콘 컴포넌트 구현
-  아이콘이 사용되고 있는 컴포넌트들 수정
<br/>
>
> COC-151 Icon 컴포넌트 구현 

- package-lock.json
- package.json
- src/components/Modal/TestCase/TestcaseItem/index.tsx
- src/components/Modal/TestCase/TestcaseItem/style.ts
- src/components/Modal/TestCase/index.tsx
- src/components/Modal/TestCase/style.ts
- src/components/_common/atoms/Icon/index.tsx
- src/components/_common/atoms/IconButton/index.tsx
- src/components/_common/atoms/IconButton/style.ts
- src/constants/modal.ts
- src/types/modal.ts
close #58 
<br/>
- 테스트 케이스 모달 구현
App.tsx
```
import { TESTCASE_INFO } from '@constants/modal';
import { useModalStore } from '@stores/useModalStore';
const { open } = useModalStore();
const handle = () => {
open('testcase', {
status: TESTCASE_INFO.status,
testcases: TESTCASE_INFO.testcases,
});
};
return (
<div>
<button
type='button'
onClick={handle}
>
테스트 케이스 모달 열기
</button>
</div>
);
}
```
constants/modal.ts
```
export const TESTCASE_INFO = {
status: 'CUSTOM',
testcases: [
{ id: 1, input: 'Input 1', output: 'Output 1', type: 'BASE' },
{ id: 2, input: 'Input 2', output: 'Output 2', type: 'BASE' },
{ id: 3, input: 'Input 3', output: 'Output 3', type: 'CUSTOM' },
{ id: 4, input: 'Input 4', output: 'Output 4', type: 'CUSTOM' },
],
};
```
<br/>
> 리뷰어가 특별히 …
> COC-153 테스트 케이스 모달 구현

- public/mockServiceWorker.js
- src/components/Modal/PasswordInput/index.tsx
- src/components/Modal/PasswordInput/style.ts
- src/components/_common/molecules/InputField/style.ts
- src/types/modal.ts
close #67 
<br/>
- PasswordInput Modal 컴포넌트 구현
- InputField 에서 password type 일때 edge일 경우 기본으로 제공되는 보이기/숨기기 아이콘 비활성화
<br/>
<br/>
```typescript
//App.tsx
import { useModalStore } from '@stores/useModalStore';
const { open } = useModalStore();
const handle = () => {
open('passwordInput', {
description: '비밀번호를 입력해주세요',
});
};
return (
<div>
<button
type='button'
onClick={handle}
>
비밀번호 입력 모달 열기
</button>
</div>
);
}
```
>
> COC-156 PasswordInput Modal 컴포넌트 구현

- src/components/Modal/Confirm/index.tsx
- src/components/Modal/Confirm/style.ts
- src/types/modal.ts
close #69 
<br/>
- Confirm Modal 컴포넌트 구현
<br/>
<br/>
```typescript
//App.tsx
import { useModalStore } from '@stores/useModalStore';
const { open } = useModalStore();
const handle = (description: string) => {
open('confirm', { description });
};
return (
<div>
<button
type='button'
onClick={() => handle('스터디 이름')}
>
스터디 참여 모달 열기
</button>
<button
type='button'
onClick={() => handle('프로그래머스 - 설탕배달')}
>
코딩 스페이스 참여 모달 열기
</button>
</div>
);
}
```
>
> COC-157 Confirm Modal 컴포넌트 구현

- src/components/_common/molecules/AvatarGroup/index.tsx
- src/components/_common/molecules/UserProfile/index.tsx
- src/main.tsx
- src/pages/CodingSpace/SpaceFinish/index.tsx
- src/pages/CodingSpace/SpaceReady/index.tsx
- src/pages/CodingSpace/SpaceStart/index.tsx
- src/pages/CodingSpace/index.tsx
- src/pages/ErrorPage/index.tsx
- src/pages/ErrorPage/style.ts
- src/pages/Loading/index.tsx
- src/pages/Loading/style.ts
- src/pages/MemberList/index.tsx
- src/pages/MyPage/index.tsx
- src/pages/SpaceCreate/index.tsx
- src/pages/SpaceList/index.tsx
- src/pages/StudyCreate/index.tsx
- src/pages/StudyDetail/index.tsx
- src/pages/StudyInfo/index.tsx
- src/pages/StudyList/index.tsx
- src/pages/StudyParticipation/index.tsx
- src/router/router.tsx
- src/types/user.ts
- vite.config.ts
close #72 
<br/>
- 라우터 설정
- 라우터 기본 Layout 
- 에러 페이지 구현
- 로딩 컴포넌트 구현
<br/>
>
> COC-161 라우터 설정

- src/api/domain/study.ts
- src/components/Study/StudyCreateForm/index.tsx
- src/constants/path.ts
- src/constants/queryKeys.ts
- src/hooks/useCreateStudy.ts
- src/hooks/useEditStudy.ts
- src/hooks/useGetStudyInfo.ts
- src/hooks/useLogIn.ts
- src/hooks/utils/useForm.ts
- src/mocks/data/study.ts
- src/mocks/handlers/study.ts
- src/pages/Study/StudyCreate/index.tsx
- src/pages/Study/StudyEdit/index.tsx
- src/router/AppRouter.tsx
- src/types/study.ts
close #86 
<br/>
- 스터디 수정 페이지 구현
- 스터디 정보 조회 api 및 모킹
- 스터디 수정 api 및 모킹
<br/>
<br/>
> COC-171 스터디 수정 페이지 구현

- src/components/Space/SpaceCard/index.tsx
- src/components/UserCard/index.tsx
- src/types/modal.ts
- src/types/space.ts
close #105 
<br/>
- TypeScript 빌드 에러 해결: 특정 필드가 맞지 않는 경우가 발생하여 빌드가 실패하고 있었습니다! 해당 문제 해결하여 올립니다!
<br/>
<br/>
> COC-176 빌드 에러 해결

- src/components/Space/SpaceNavbar/index.tsx
- src/constants/modal.ts
- src/hooks/ide/useRunIDE.ts
- src/hooks/ide/useSubmitIDE.ts
- src/hooks/space/useCompleteSpace.ts
- src/hooks/space/useStartSpace.ts
- src/pages/Space/SpaceDetail/index.tsx
- src/pages/Space/SpaceFeedback/index.tsx
- src/pages/Space/SpaceFinish/index.tsx
- src/pages/Space/SpaceRunning/index.tsx
- src/pages/Space/SpaceWaiting/index.tsx
close #120 
<br/>
스터디 쪽 api 연결 테스트를 위해 잠시 스페이스 코드를 제외해서 병합하겠습니다!
<br/>
<br/>
> COC-184 테스트: 스페이스 코드 제외

- src/api/domain/user.ts
- src/components/Slider/style.ts
- src/constants/api.ts
- src/hooks/user/useGetJoinedSpaceList.ts
- src/hooks/user/useGetJoinedStudyList.ts
- src/mocks/data/space/getSpaceListData.ts
- src/mocks/data/study/getStudyListData.ts
- src/mocks/handlers/user.ts
- src/pages/MyPage/MySpace/index.tsx
- src/pages/MyPage/MySpace/style.ts
- src/pages/MyPage/MyStudy/index.tsx
- src/pages/MyPage/MyStudy/style.ts
close #124 
<br/>
- 마이페이지 코딩스페이스 무한 스크롤 구현
- 마이페이지 스터디 무한 스크롤 구현
<br/>
<br/>
>
> COC-185 마이페이지 무한 스크롤 구현

- .env
- src/api/domain/study.ts
- src/components/UserCard/index.tsx
- src/components/UserCard/style.ts
- src/constants/queryKeys.ts
- src/hooks/study/useGetMemberList.ts
- src/hooks/utils/useScroll.ts
- src/mocks/data/study/getStudyMemberListData.ts
- src/mocks/data/user.ts
- src/mocks/handlers/space.ts
- src/mocks/handlers/study.ts
- src/pages/Space/SpaceList/index.tsx
- src/pages/Study/MemberList/index.tsx
- src/pages/Study/MemberList/style.ts
- src/types/user.ts
- src/utils/extendData.ts
- src/utils/formatDate.ts
close #102 
<br/>
- 멤버 목록 컴포넌트 구현 (MemberList)
- useGetMemeberList 커스텀 훅으로 멤버 목록 조회
- infiniteQuery를 사용한 무한 스크롤 구현
- useScroll 을 통해 무한 스크롤 시 사용되는 커스텀 훅 구현
- observerRef, isFetching 반환
- intersectionObserver 사용 
- 기존 스페이스에서도 사용했었음
- 스페이스에서도 useScroll 적용
<br/>
<br/>
>
> COC-110 스터디 내 멤버 목록 조회 구현

- src/components/_common/atoms/EmptyResult/index.tsx
- src/components/_common/atoms/EmptyResult/style.ts
- src/constants/common.ts
- src/mocks/data/study/getStudyListData.ts
- src/pages/Loading/index.tsx
- src/pages/Loading/style.ts
- src/pages/MyPage/MySpaceList/style.ts
- src/pages/MyPage/MyStudyList/style.ts
- src/pages/Space/SpaceList/index.tsx
- src/pages/Space/SpaceList/style.ts
- src/pages/Study/StudyList/index.tsx
- src/pages/Study/StudyList/style.ts
close #130 
<br/>
- Empty Result 이미지 적용
- 로딩 애니메이션 개선
<br/>
스터디 목록이 비었을 때.
스페이스 목록이 비었을 때.
참여한 스터디 목록이 비었을 때.
참여한 스페이스 목록이 비었을 때.
로딩 애니메이션
<br/>
스터디 목록 빈 경우 확인시 src/mocks/data/study/getStudyListData.ts 스터디 목록 조회 빈배열 사용.
```typescript
export const getStudyListResponse = {
code: 3000,
message: '전체 스터디 조회에 성공했습니다.',
result: {
totalStudyCount: 0, // 스터디 개수를 0으로 설정
studies: [], // 빈 배열로 변경
lastId: null, // 더 이상 불러올 데이터가 없음을 의미
},
};
export const getStudyListErrorResponse = {
code: 4200,
message: '스터디 목록 조회에 실패했습니다.',
};
```
스페이스 목록 빈 경우 확인시 src/mocks/data/space/getSpaceListData.ts  스페이스 목록 조회 빈배열 사용.
```typescript
export const getSpaceListResponse = {
code: 4000,
message: '코딩 스페이스 목록 조회에 성공했습니다.',
result: {
codingSpaces: [], // 빈 배열로 설정하여 data?.pages.length === 0 조건 만족
lastId: null, // 마지막 ID도 …
```
> COC-190 Empty Result 이미지 적용 및 로딩 애니메이션 개선

- src/components/_common/atoms/MoveTopButton/style.ts
- src/constants/common.ts
- src/pages/MainLayout/Footer/index.tsx
- src/pages/MainLayout/Footer/style.ts
close #144  
<br/>
- 하단 바 메뉴 아이템 키 참조 문제 해결
- 맨위로 이동 버튼 크기 축소
- 메뉴 아이템 줄 바꿈 되는 문제 해결
- 메뉴 아이템 클릭 이벤트 활성화 (현재는 주석으로 대체)
<br/>
<br/>
>
> COC 203 Footer 이슈사항 해결

- src/api/domain/space.ts
- src/components/Modal/Login/style.ts
- src/components/NavBar/index.tsx
- src/components/Space/SpaceCard/SpaceCardHeader/index.tsx
- src/components/Space/SpaceCard/SpaceCardHeader/style.ts
- src/components/Space/SpaceCard/index.tsx
- src/components/Space/SpaceCard/style.ts
- src/components/Space/SpaceForm/index.tsx
- src/components/Study/StudyDescription/DescriptionHeader/index.tsx
- src/components/Study/StudyForm/index.tsx
- src/components/_common/atoms/Icon/index.tsx
- src/components/_common/molecules/InputDropdown/index.tsx
- src/components/_common/molecules/SelectDropdown/index.tsx
- src/components/_common/molecules/UserProfile/index.tsx
- src/constants/api.ts
- src/constants/common.ts
- src/hooks/space/useDeleteSpace.ts
- src/hooks/utils/useDropdown.ts
- src/hooks/utils/useForm.ts
- src/pages/MyPage/MySpaceList/index.tsx
- src/pages/Space/SpaceList/index.tsx
- src/pages/Study/StudyCreate/index.tsx
- src/pages/Study/StudyEdit/index.tsx
- src/utils/validators/spaceValidators.ts
- src/utils/validators/studyValidators.ts
close #149 
<br/>
- 로그인 모달 버튼 스타일 수정
- 유저 프로필 클릭 시 로그인 상태 확인 추가
- useForm 리팩토링 -> submit 시 유효성 검사되도록 수정, 실패 시 토스트 메시지
- 코딩 스페이스 삭제 구현
- 드롭다운 ref 훅으로 분리
- 삭제 시 UI 즉시 반영으로 API 요청 최적화 ( 목록 조회 캐시 무효화 제거 )
<br/>
<br/>
> COC-206 이슈사항 해결 및 코딩 스페이스 삭제

- vite.config.ts
close #
<br/>
- 기능에서 어떤 부분이
- 구현되었는지 설명해주세요
<br/>
<br/>
>
> fix(#1): yorkie 에러

- src/constants/api.ts
- src/hooks/utils/useYorkie.ts
- src/pages/Space/SpaceFeedback/index.tsx
- vite.config.ts
close #160 
<br/>
- 코딩 스페이스 테스트 케이스 추가, 삭제 에러 해결
<br/>
<br/>
>
> COC-211: 코딩 스페이스 테스트 케이스 추가, 삭제 에러 해결

- src/constants/api.ts
- vite.config.ts
close #
<br/>
- oAuth 개발 모드 제거
<br/>
<br/>
>
> fix(#2): oAuth 개발 모드 제거

- src/components/Space/SpaceNavbar/index.tsx
- src/hooks/space/useEnterSpace.ts
- src/pages/Space/SpaceFeedback/index.tsx
- src/pages/Space/SpaceFinish/index.tsx
- src/pages/Space/SpaceRunning/index.tsx
- src/pages/Space/SpaceWaiting/index.tsx
close #167 
<br/>
- 코딩 스페이스 대기 페이지 뒤로 가기 추가
<br/>
<br/>
>
> COC-215 코딩 스페이스 대기 페이지 뒤로 가기 추가

- src/components/Modal/Confirm/style.ts
- src/components/Modal/PasswordInput/style.ts
- src/components/Space/MemberCard/index.tsx
- src/components/Space/MemberCard/style.ts
- src/components/Space/SpaceCard/index.tsx
- src/components/Space/SpaceCard/style.ts
- src/components/Space/SpaceForm/style.ts
- src/components/Study/StudyForm/style.ts
- src/components/_common/atoms/IconButton/style.ts
- src/components/_common/molecules/AvatarGroup/style.ts
- src/pages/MainLayout/Footer/style.ts
- src/pages/MainLayout/index.tsx
- src/pages/MainLayout/style.ts
- src/pages/MyPage/MyStudyList/style.ts
- src/pages/MyPage/style.ts
- src/pages/Space/SpaceList/SpaceFilterTab/style.ts
- src/pages/Study/MemberList/style.ts
- src/pages/Study/StudyList/StudyFilterTab/style.ts
- src/pages/Study/StudyList/style.ts
- src/styles/font.ts
- src/styles/globalStyles.ts
close #166 
<br/>
- 반응형 구현
- 추후 모바일 반응형 디자인이 나오면 해당사항 반영해서 수정하도록 하겠습니다!
<br/>
<br/>
> COC-214 반응형 구현

- src/components/_common/atoms/MoveTopButton/style.ts
- src/mocks/data/user/getMyInfoData.ts
- src/mocks/data/user/getUserInfoData.ts
- src/mocks/data/user/getUserSpaceListData.ts
- src/mocks/data/user/getUserStudyListData.ts
- src/mocks/data/user/uploadUserImage.ts
- src/mocks/handlers/user.ts
- src/types/user.ts
close #150 
<br/>
- 유저 관련 모킹 데이터 추가
- 유저 관련 핸들러 구현
- 유저 정보 조회 | 내 정보 조회 | 내 스터디 조회 | 내 스페이스 조회 | 프로필 이미지 업로드 | 내 프로필 수정 
<br/>
<br/>
> 핸들러에서 수정 될 부분 있으면 말씀해 주세요
> COC-207 유저 관련 모킹 데이터 및 핸들러 추가

- .env
- src/components/Space/SpaceCard/SpaceCardHeader/index.tsx
- src/components/Space/SpaceCard/SpaceCardHeader/style.ts
- src/components/Space/SpaceCard/index.tsx
- src/components/Space/SpaceForm/style.ts
- src/components/Study/StudyForm/index.tsx
- src/components/Study/StudyForm/style.ts
- src/components/_common/atoms/Icon/index.tsx
- src/components/_common/atoms/MoveTopButton/index.tsx
- src/components/_common/atoms/MoveTopButton/style.ts
- src/components/_common/molecules/AvatarGroup/index.tsx
- src/hooks/utils/useDropdown.ts
- src/pages/MainLayout/Footer/index.tsx
- src/pages/Study/StudyCreate/index.tsx
- src/pages/Study/StudyEdit/index.tsx
- src/types/space.ts
- src/types/study.ts
close #159 
<br/>
- 타입 및 필드 api 와 로직에 맞게 정리
- 드롭다운 버튼 클릭 시 이벤트 버블링 문제 해결
- 스페이스 리스트 드롭다운 오버레이 시 닫기 적용
- 하단 라이센스 변경
- 스크롤 버튼 스타일링 수정
- 미수정된 디자인 변경
<br/>
<br/>
> COC-210 2차 프론트 이슈 사항 해결

- index.html
- src/api/domain/ide.ts
- src/api/domain/space.ts
- src/components/Space/CodingWorkspace/CodeExecutor/SubmissionPanel/index.tsx
- src/components/Space/CodingWorkspace/CodeExecutor/SubmissionPanel/style.ts
- src/components/Space/CodingWorkspace/CodeExecutor/index.tsx
- src/components/Space/CodingWorkspace/index.tsx
- src/components/Space/SubmissionItem/index.tsx
- src/components/Space/SubmissionItem/style.ts
- src/constants/api.ts
- src/hooks/space/useSubmission.ts
- src/hooks/utils/useYorkie.ts
- src/mocks/handlers/study.ts
- src/pages/Space/SpaceFeedback/index.tsx
- src/pages/Space/SpaceFinish/index.tsx
- src/pages/Space/SpaceRunning/index.tsx
- src/pages/Space/SpaceWaiting/index.tsx
- src/types/space.ts
close #170 
<br/>
- 코딩 스페이스 코드 제출 구현 
-  yorkie 에러 해결
- 코드 리펙토링
- 피드백 페이지에서 종료 페이지 전환 시 발생하는 에러 해결
<br/>
>
> Coc 216 코딩 스페이스 코드 제출 구현 및 yorkie 에러 해결, 코드 리펙토링

- src/components/Space/CodingWorkspace/CodeExecutor/ExecutionPanel/index.tsx
- src/components/Space/CodingWorkspace/CodeExecutor/index.tsx
- src/components/Space/CodingWorkspace/index.tsx
- src/hooks/utils/useYorkie.ts
- src/pages/Space/SpaceFeedback/index.tsx
- src/pages/Space/SpaceRunning/index.tsx
close #175 
<br/>
- 코드 실행 에러 수정
<br/>
>
> COC-218: 코드 실행 에러 수정

- src/api/domain/study.ts
- src/hooks/study/useDeleteStudy.ts
- src/mocks/handlers/study.ts
close #177 
<br/>
- 스터디 삭제 API 오류 수정
- delete 요청 -> post 요청으로 수정
<br/>
<br/>
>
> COC-219 스터디 삭제 API 오류 수정

- src/components/Modal/TestCase/index.tsx
- src/components/_common/atoms/TestCaseItem/style.ts
- src/constants/api.ts
- src/pages/Space/SpaceFeedback/index.tsx
- src/pages/Space/SpaceRunning/index.tsx
close #
<br/>
-ERROR Message 추가, testCase Textarea로 변경
<br/>
<br/>
>
> FIX: ERROR Message 추가, testCase Textarea로 변경

- src/components/Space/CodingWorkspace/CodeExecutor/SubmissionPanel/index.tsx
- src/components/Space/CodingWorkspace/CodeExecutor/SubmissionPanel/style.ts
- src/pages/Space/SpaceRunning/index.tsx
close #
<br/>
- 기능에서 어떤 부분이
- 구현되었는지 설명해주세요
<br/>
<br/>
>
> Fix: 코드 실행, 제출 refactor

- README.md
close #185 
<br/>
- 개발 기간 정리
- 기술 스택 정리
- 협업 방식 정리
- 코코무 개발 이야기 정리
<br/>
<br/>
> Docs/#185 프론트 리드미 기술 문서 작성

- package-lock.json
- package.json
- src/main.tsx
close #187 
<br/>
- 개발 환경에서 발생하는 콘솔 에러를 자동으로 분석해주는 기능을 추가했습니다.
- 해당 기능은 직접 라이브러리로 제작하여 프로젝트에 적용했습니다. 사용 중 문제가 있다면 언제든 알려주세요!
<br/>
<br/>
> Feat/#187 개발 환경에서 GPT 기반 에러 분석기 적용

- .github/workflows/deploy.yml
close #196 
<br/>
- IAM 사용자 생성 및 권한 부여 (S3 + CloudFront)
- 액세스 키 발급 및 GitHub Actions Secrets 등록
- GitHub Actions workflow 파일 작성 (.github/workflows/deploy.yml)
배포 성공, 실패 시 디스코드에 알람이 갑니다!
<br/>
<br/>
> Feat/#196 GitHub Actions를 통한 S3 + CloudFront 배포 자동화 설정

- .github/workflows/deploy.yml
close #198 
<br/>
- 디스코드 알람 에러 해결
- 수동 배포 활성화
<br/>
<br/>
> Fix/#198 배포 시 디스코드 알람 에러 해결
